#!/bin/bash
path="/storage/roms/"
mkdir -p "$path"Atari2600
mkdir -p "$path"Atari7800
mkdir -p "$path"AtariJaguar
mkdir -p "$path"AtariLynx
mkdir -p "$path"AtariST
mkdir -p "$path"BandaiWonderSwanColor
mkdir -p "$path"BandaiWonderSwan
mkdir -p "$path"CaveStory
mkdir -p "$path"DOOM
mkdir -p "$path"FBAlphaArcadeGames
mkdir -p "$path"GCEVectrex
mkdir -p "$path"Lutro
mkdir -p "$path"MAME
mkdir -p "$path"MicrosoftMSX2
mkdir -p "$path"MicrosoftMSX
mkdir -p "$path"NECPCEngineSuperGrafx
mkdir -p "$path"NECPCEngineTurboGrafx16
mkdir -p "$path"NintendoGameBoyAdvance
mkdir -p "$path"NintendoGameBoyColor
mkdir -p "$path"NintendoGameBoy
mkdir -p "$path"NintendoNintendo64
mkdir -p "$path"NintendoNintendoEntertainmentSystem
mkdir -p "$path"NintendoSatellaview
mkdir -p "$path"Snes
mkdir -p "$path"NintendoVirtualBoy
mkdir -p "$path"Quake1
mkdir -p "$path"ScummVM
mkdir -p "$path"Sega32X
mkdir -p "$path"SegaGameGear
mkdir -p "$path"SegaMasterSystemMarkIII
mkdir -p "$path"SegaGenesis
mkdir -p "$path"SegaPICO
mkdir -p "$path"SegaSG-1000
mkdir -p "$path"SinclairZXSpectrum+3
mkdir -p "$path"SNKNeoGeoPocketColor
mkdir -p "$path"SNKNeoGeoPocket
mkdir -p "$path"SonyPlayStationPortable
mkdir -p "$path"SonyPlayStation